#!/usr/bin/env python3

# Import required Python code.
import roslib
import rospy

from autonomous_node.main import AutonomousNode

NODE_NAME = 'autonomous_node'
roslib.load_manifest(NODE_NAME)

if __name__ == '__main__':
    rospy.init_node(NODE_NAME)
    try:
        node = AutonomousNode()
    except rospy.ROSInterruptException:
        pass
